services:
  student-center-auth:
    container_name: student-center-auth-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"   
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./dataprotection-keys:/home/app/.aspnet/DataProtection-Keys