version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - student-center-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  student-center-auth:
    container_name: student-center-auth-api
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQHost=rabbit
      - RabbitMQPort=5672
      - RabbitMQUser=guest
      - RabbitMQPassword=guest
    volumes:
      - ./dataprotection-keys:/home/app/.aspnet/DataProtection-Keys   
    networks:
      - student-center-net
    depends_on:
      - rabbitmq

networks:
  student-center-net:
    external: true



